### ISSUE TITLE
Cannot import third party modules

### ISSUE THREAD

**Issue by joshmillgate** [rishavs/vanillajs-spa#1]
Hey, I'm playing with your SPA setup and whilst just trying to import modules through any of the JS pages I'm getting the following error:

`Uncaught TypeError: Failed to resolve module specifier "uuid". Relative references must start with either "/", "./", or "../".`

Can't find anything online about this and I'm new to JS so not sure if I'm overlooking something simple and fundamental.

**Comment by rishavs** [comment]
Can I take a look at your code? Maybe you can put up a gist/jsfiddle, if you dont have a github project?

From some other discussions like https://github.com/openlayers/openlayers/issues/7766, it seems to be an issue with trying to import something which isn't explicitly exported.

**Comment by joshmillgate** [comment]
I'm literally just cloning the repo and installing uuid via npm and then adding 
`import uuid from 'uuid';`

to the top of App.js

**Comment by rishavs** [comment]
One way is to simply add;
```
        <script src="http://wzrd.in/standalone/uuid%2Fv5@latest"></script>
        <script>
            console.log(uuidv5('http://example.com/hello', uuidv5.URL)); // -> v5 UUID
        </script> 
```
in your index.html

I think importing browser specific js modules should work, but they need to end in .js and have a module.exports in them. For example, I took https://raw.githubusercontent.com/pnegri/uuid-js/master/lib/uuid.js

and changed the last line to `export default UUIDjs;` and added an import in my app.js as;
`import uuid from './services/uuid.js'`. This worked fine.

You may also consider a browser side bundler like browserify.

I don't think you should call any module from npm. You wouldn't be able to use it unless you are serving these files from a static npm server.

I haven't really spent much time on this kind of issue but I am sure more elegant ways of doing fixing it should be there.

**Comment by rishavs** [comment]
@joshmillgate I hope you have been unblocked. I am closing this issue for now.
