### ISSUE TITLE
How do I can launch this kind of project for production?

### ISSUE THREAD

**Issue by efraxpc** [rishavs/vanillajs-spa#4]
Hello friend, first of all thaks to your awesome project, it helped to me to improve my JS abilities, ok, so I wanted to tell you *How do I can launch this kind of project for a production environment* ??

I'm a begginer in JS

Thanks in advace

**Comment by rishavs** [comment]
You will need an api server. nodejs has some very simple but powerful ones.
Or perhaps the simplest would be to use Firebase.

Then you will need to host your SPA app on a CDN provider like cloudflare.

**Comment by efraxpc** [comment]
Thank you very much
